# Generated by Django 5.0.6 on 2024-06-06 11:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.AddField(
            model_name='task',
            name='taskTitle',
            field=models.CharField(default=datetime.datetime(2024, 6, 6, 11, 31, 3, 178306, tzinfo=datetime.timezone.utc), max_length=30),
            preserve_default=False,
        ),
    ]
